openapi: 3.0.0
info:
  title: AquaManage API
  version: 1.0.0
  description: API for managing aquarium actuators (Marine and Planted Tanks)
servers:
  - url: http://localhost:8081
    description: Local development server for the AquaManage API

paths:
  /actuators/Marine/greet:
    get:
      summary: Greeting from Marine Actuator
      description: Returns a greeting message from the Marine Actuator
      responses:
        '200':
          description: Greeting message
          content:
            text/plain:
              schema:
                type: string

  /actuators/Marine/set-saltwater-ratio:
    post:
      summary: Set saltwater mixer ratio for marine tank
      description: Set the saltwater mixer ratio for the marine tank
      parameters:
        - name: ratio
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Saltwater mixer ratio successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Marine/set-calcium-rate:
    post:
      summary: Set calcium dosing rate for marine tank
      description: Set the calcium dosing rate for the marine tank in mL/hour
      parameters:
        - name: rate
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Calcium dosing rate successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Marine/set-alkalinity-rate:
    post:
      summary: Set alkalinity dosing rate for marine tank
      description: Set the alkalinity dosing rate for the marine tank in mL/hour
      parameters:
        - name: rate
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Alkalinity dosing rate successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Marine/set-skimmer-efficiency:
    post:
      summary: Set skimmer efficiency for marine tank
      description: Set the skimmer efficiency for the marine tank in percentage
      parameters:
        - name: efficiency
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Skimmer efficiency successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Marine/set-heater-temp:
    post:
      summary: Set heater temperature for marine tank
      description: Set the heater temperature for the marine tank in Celsius
      parameters:
        - name: temperature
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Heater temperature successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Marine/set-light-duration:
    post:
      summary: Set light time duration for marine tank
      description: Set the light duration for the marine tank in minutes
      parameters:
        - name: duration
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Light time duration successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Marine/set-water-pump-rate:
    post:
      summary: Set water pump flow rate for marine tank
      description: Set the water pump flow rate for the marine tank in L/h
      parameters:
        - name: flowRate
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Water pump flow rate successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Marine/set-auto-water-change:
    post:
      summary: Set auto water change volume for marine tank
      description: Set the auto water change volume for the marine tank in liters
      parameters:
        - name: volume
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Auto water change volume successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Planted/set-co2-rate:
    post:
      summary: Set CO2 injection rate for planted tank
      description: Set the CO2 injection rate for the planted tank in bubbles/minute
      parameters:
        - name: rate
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: CO2 injection rate successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Planted/set-nutrient-rate:
    post:
      summary: Set nutrient dosing rate for planted tank
      description: Set the nutrient dosing rate for the planted tank in mL/hour
      parameters:
        - name: rate
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Nutrient dosing rate successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Planted/set-heater-temp:
    post:
      summary: Set heater temperature for planted tank
      description: Set the heater temperature for the planted tank in Celsius
      parameters:
        - name: temperature
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Heater temperature successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Planted/set-light-duration:
    post:
      summary: Set light time duration for planted tank
      description: Set the light duration for the planted tank in minutes
      parameters:
        - name: duration
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Light time duration successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Planted/set-water-pump-rate:
    post:
      summary: Set water pump flow rate for planted tank
      description: Set the water pump flow rate for the planted tank in L/h
      parameters:
        - name: flowRate
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Water pump flow rate successfully set
          content:
            text/plain:
              schema:
                type: string

  /actuators/Planted/set-auto-water-change:
    post:
      summary: Set auto water change volume for planted tank
      description: Set the auto water change volume for the planted tank in liters
      parameters:
        - name: volume
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Auto water change volume successfully set
          content:
            text/plain:
              schema:
                type: string
